### ISSUE TITLE
du-mocks

### ISSUE THREAD

**Issue by SvarogZ** [1337joe/du-mocks#4]
Could you please update the website?
This is the most useful tool for me.
https://du.w3asel.com/du-mocks/mock-codex/index.html

**Comment by 1337joe** [comment]
The reset wiped out my testing facility and I haven't had enough time to play (or quanta) to effectively build it back up. That said, I've got the base Element class updated (on the ptr branch) so now I have a foundation to build on as I have time.

Also of note, github pages is intended to be the new home for the web/mock codex:
https://1337joe.github.io/du-mocks/web-codex-pts/

That link is to the pts version, since it's what I've started to update. Once it's at least in a consistent state I'll merge it to main and the non-pts codex pages will update.
